// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4LSrToqTumkKN88BqN4vEABmyGkXarpY',
    appId: '1:647818256865:web:96298b88fe29ca487ab2a0',
    messagingSenderId: '647818256865',
    projectId: 'placementtask',
    authDomain: 'placementtask.firebaseapp.com',
    storageBucket: 'placementtask.firebasestorage.app',
    measurementId: 'G-RTX5MKF522',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2rVCHb1H1sZOg2pktyUdLslz1mknKSGI',
    appId: '1:647818256865:android:a6a5a6f595b968a57ab2a0',
    messagingSenderId: '647818256865',
    projectId: 'placementtask',
    storageBucket: 'placementtask.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrC_xasqlkBcTniRi1DrZClzfgjP7BtZc',
    appId: '1:647818256865:ios:22f6652c99388b817ab2a0',
    messagingSenderId: '647818256865',
    projectId: 'placementtask',
    storageBucket: 'placementtask.firebasestorage.app',
    iosBundleId: 'com.example.placementtask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrC_xasqlkBcTniRi1DrZClzfgjP7BtZc',
    appId: '1:647818256865:ios:22f6652c99388b817ab2a0',
    messagingSenderId: '647818256865',
    projectId: 'placementtask',
    storageBucket: 'placementtask.firebasestorage.app',
    iosBundleId: 'com.example.placementtask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4LSrToqTumkKN88BqN4vEABmyGkXarpY',
    appId: '1:647818256865:web:cd51c3c068b01d1c7ab2a0',
    messagingSenderId: '647818256865',
    projectId: 'placementtask',
    authDomain: 'placementtask.firebaseapp.com',
    storageBucket: 'placementtask.firebasestorage.app',
    measurementId: 'G-255SJ8972Y',
  );
}
